/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tt1.trabajo.utilidades.modelo;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Solicitud
 */
@JsonPropertyOrder({
  Solicitud.JSON_PROPERTY_CANTIDADES_INICIALES,
  Solicitud.JSON_PROPERTY_NOMBRE_ENTIDADES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-25T13:16:07.296526700+01:00[Europe/Madrid]", comments = "Generator version: 7.21.0")
public class Solicitud {
  public static final String JSON_PROPERTY_CANTIDADES_INICIALES = "cantidadesIniciales";
  @javax.annotation.Nullable
  private JsonNullable<List<Integer>> cantidadesIniciales = JsonNullable.<List<Integer>>undefined();

  public static final String JSON_PROPERTY_NOMBRE_ENTIDADES = "nombreEntidades";
  @javax.annotation.Nullable
  private JsonNullable<List<String>> nombreEntidades = JsonNullable.<List<String>>undefined();

  public Solicitud() {
  }

  public Solicitud cantidadesIniciales(@javax.annotation.Nullable List<Integer> cantidadesIniciales) {
    this.cantidadesIniciales = JsonNullable.<List<Integer>>of(cantidadesIniciales);
    
    return this;
  }

  public Solicitud addCantidadesInicialesItem(Integer cantidadesInicialesItem) {
    if (this.cantidadesIniciales == null || !this.cantidadesIniciales.isPresent()) {
      this.cantidadesIniciales = JsonNullable.<List<Integer>>of(new ArrayList<>());
    }
    try {
      this.cantidadesIniciales.get().add(cantidadesInicialesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get cantidadesIniciales
   * @return cantidadesIniciales
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<Integer> getCantidadesIniciales() {
        return cantidadesIniciales.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CANTIDADES_INICIALES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Integer>> getCantidadesIniciales_JsonNullable() {
    return cantidadesIniciales;
  }
  
  @JsonProperty(JSON_PROPERTY_CANTIDADES_INICIALES)
  public void setCantidadesIniciales_JsonNullable(JsonNullable<List<Integer>> cantidadesIniciales) {
    this.cantidadesIniciales = cantidadesIniciales;
  }

  public void setCantidadesIniciales(@javax.annotation.Nullable List<Integer> cantidadesIniciales) {
    this.cantidadesIniciales = JsonNullable.<List<Integer>>of(cantidadesIniciales);
  }

  public Solicitud nombreEntidades(@javax.annotation.Nullable List<String> nombreEntidades) {
    this.nombreEntidades = JsonNullable.<List<String>>of(nombreEntidades);
    
    return this;
  }

  public Solicitud addNombreEntidadesItem(String nombreEntidadesItem) {
    if (this.nombreEntidades == null || !this.nombreEntidades.isPresent()) {
      this.nombreEntidades = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.nombreEntidades.get().add(nombreEntidadesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get nombreEntidades
   * @return nombreEntidades
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<String> getNombreEntidades() {
        return nombreEntidades.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_NOMBRE_ENTIDADES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getNombreEntidades_JsonNullable() {
    return nombreEntidades;
  }
  
  @JsonProperty(JSON_PROPERTY_NOMBRE_ENTIDADES)
  public void setNombreEntidades_JsonNullable(JsonNullable<List<String>> nombreEntidades) {
    this.nombreEntidades = nombreEntidades;
  }

  public void setNombreEntidades(@javax.annotation.Nullable List<String> nombreEntidades) {
    this.nombreEntidades = JsonNullable.<List<String>>of(nombreEntidades);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Solicitud solicitud = (Solicitud) o;
    return equalsNullable(this.cantidadesIniciales, solicitud.cantidadesIniciales) &&
        equalsNullable(this.nombreEntidades, solicitud.nombreEntidades);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(cantidadesIniciales), hashCodeNullable(nombreEntidades));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Solicitud {\n");
    sb.append("    cantidadesIniciales: ").append(toIndentedString(cantidadesIniciales)).append("\n");
    sb.append("    nombreEntidades: ").append(toIndentedString(nombreEntidades)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

